apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  namespace: api
  name: azure-ohkeyvault # This is just a friendly name
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "57a4fde6-79ab-4180-9346-b7c5ac017894"
    keyvaultName: "ka-akvault" # This has to  match with your key vault name
    cloudName: ""          # will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLUSER1
          objectType: secret  
          objectAlias: SQL_USER      
          objectVersion: ""         #
        - |
          objectName: SQLPASSWORD
          objectType: secret  
          objectAlias: SQL_PASSWORD      
          objectVersion: ""         #
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret        
          objectVersion: ""         #
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret        
          objectVersion: ""         #
    resourceGroup: "[Your resource group]"            
    subscriptionId: "[Your Subscription ID]"   
    tenantId: "[Your Tenant ID]"
